arm_controller:
    type: position_controllers/JointTrajectoryController
    joints:
       - BJ
       - SJ
       - EJ
       - W1J
       - W2J
    constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      BJ: {trajectory: 0.1, goal: 0.1}
      SJ: {trajectory: 0.1, goal: 0.1}
      EJ: {trajectory: 0.1, goal: 0.1}
      W1J: {trajectory: 0.1, goal: 0.1}
      W2J: {trajectory: 0.1, goal: 0.1}
    stop_trajectory_duration: 0.5
    state_publish_rate:  25
    action_monitor_rate: 10
/gazebo_ros_control:
    pid_gains:
      BJ: {p: 1000.0, i: 100.0, d: 10.0}
      SJ: {p: 1000.0, i: 100.0, d: 10.0}
      EJ: {p: 1000.0, i: 100.0, d: 10.0}
      W1J: {p: 1000.0, i: 100.0, d: 10.0}
      W2J: {p: 100.0, i: 0.0, d: 0.0}
      
      
      