cobot_controller:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers --------------------------------------
  joint_position_controller:
    type: position_controllers/JointTrajectoryController
    joint: [base_joint,shoulder,elbow,wrist] 
    constraints:
       goal_time: 0.6
       stopped_velocity_tolerance: 0.05
       base_joint: {trajectory: 0.1, goal: 0.1}
       shoulder: {trajectory: 0.1, goal: 0.1}
       elbow: {trajectory: 0.1, goal: 0.1}
       wrist: {trajectory: 0.1, goal: 0.1}
      
    stop_trajectory_duration: 0.5
    state_publish_rate:  25
    action_monitor_rate: 10
    pid: {p: 100.0, i: 0.01, d: 10.0}
